version: "3"

services:
  db:
    build:
      context: .
      dockerfile: DockerfileDB
    restart: on-failure
#    command: ["redis-server", "--bind", "127.0.0.1", "--port", "6379"]
    networks:
      - sanet

  cowboy_server:
    build:
      context: .
      dockerfile: DockerfileSERVER
    restart: on-failure
    ports:
      - 8081:8081 
    networks:
      - sanet

networks:
  sanet:
    driver: bridge